name: Katrin Bloms
markdown: kramdown
permalink: /blog/:title

collections:
  slides:
    output: true
    permalink: /:collection/:path

defaults:
  -
    scope:
      path: ""
      type: "slides"
    values:
      layout: "slides"