name: Katrin Bloms
markdown: kramdown
permalink: /blog/:title

exclude:
  - README.md
  - reveal.js/index.html
  - reveal.js/plugin/markdown/example.html
  - reveal.js/test/
  - reveal.js/*.md
  - reveal.js/Gruntfile.js
  - reveal.js/package.json
  - reveal.js/LICENSE